import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { format } from 'prettier';

async function main() {
  await mkdir('src/lib/marketplace/abi', { recursive: true });
  for (const contract of [
    'AuctionHouse',
    'AssetRevenueVault',
    'AssetLaunchCoordinator',
    'ENSAssetRegistry',
    'DemoUSDC',
  ]) {
    const artifact = JSON.parse(
      await readFile(`contracts/out/${contract}.sol/${contract}.json`, 'utf8'),
    );
    const source = `// Generated by npm run contracts:abi.\nexport const ${contract === 'ENSAssetRegistry' ? 'ensAssetRegistry' : contract[0].toLowerCase() + contract.slice(1)}Abi = ${JSON.stringify(artifact.abi)} as const;\n`;
    await writeFile(
      `src/lib/marketplace/abi/${contract}.ts`,
      await format(source, { parser: 'typescript', singleQuote: true }),
    );
  }
  console.log('Exported marketplace contract ABIs.');
}
main().catch(() => {
  console.error('ABI export failed.');
  process.exitCode = 1;
});
